# Generated by Django 4.2 on 2023-04-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
